use_frameworks!
platform :ios, '12.1'

target 'BikeApi_Tests' do
  
  pod 'BikeApi', :path => '../'
  pod 'Alamofire', '~> 4.8'
  pod 'KeychainAccess'
  pod 'ObjectMapper'
  pod 'PromiseKit', '~> 6.8.3'
  pod 'MSAL'

end
